image: atlassian/default-image:3

pipelines:
  branches:
    develop:
     - step:
         name: 'Deployment to Staging'
         deployment: Staging
         script:
          - pipe: atlassian/ssh-run:0.3.0
            variables:
              SSH_USER: 'ubuntu'
              SERVER: 'getsetadmit.com'
              SSH_KEY: $PROD_SSH_KEY
              MODE: 'script'
              COMMAND: 'deployStage.sh'
    master:
     - step:
         name: 'Deployment to Production'
         deployment: Production
         script:
          - pipe: atlassian/ssh-run:0.3.0
            variables:
              SSH_USER: 'ubuntu'
              SERVER: 'getsetadmit.com'
              SSH_KEY: $PROD_SSH_KEY
              MODE: 'script'
              COMMAND: 'deployProd.sh'